name: doom
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - gymnasium-all
  - pyyaml
  - pillow
  - pynput
  - pyarrow
  - fastparquet
  - opencv
  - imageio
  - numpy
  - pandas
  - tqdm
  - pip:
      - vizdoom